In [19]:
#1
import numpy as np
Z = np.random.random((10,3))
print(Z)
[x[np.abs(x-0.5).argmin()] for x in Z]





[[0.83153082 0.36569147 0.85447392]
 [0.18728898 0.91628647 0.49620486]
 [0.87854582 0.02383883 0.31881709]
 [0.77447308 0.53958924 0.61291328]
 [0.31099012 0.36995852 0.25629322]
 [0.692691   0.98324689 0.07835168]
 [0.3635816  0.04051075 0.08883141]
 [0.94550338 0.58554203 0.54634706]
 [0.90812489 0.51755916 0.38907944]
 [0.23587757 0.66813215 0.29144816]]


[0.3656914657654009,
 0.49620485599498076,
 0.31881708772410966,
 0.5395892420915205,
 0.36995851991199724,
 0.6926909952250965,
 0.3635815952528192,
 0.5463470639447329,
 0.5175591575217368,
 0.6681321513745261]

In [23]:
#2
import numpy as np
Z = np.random.random((3, 3))
print(Z)
print(Z.sum(axis = 1)/ Z.min(axis = 0))

[[0.54767641 0.16289292 0.64015358]
 [0.39130996 0.2429438  0.11693008]
 [0.02035656 0.67871314 0.04112995]]
[66.35319056  4.61151918 17.99660848]


In [36]:
#3
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = x==0
print (x[1:][zero[:-1]].max())

5
